name: Build

on:
  push:
    branches:
    - main

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Check commit message
        uses: kaisugi/action-regex-match@v1.0.1
        id: regex-match
        with:
          text: ${{ github.event.head_commit.message }}
          regex: '^[0-9]+\.[0-9]+\.[0-9]+$'

      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
        
      - name: Install dependencies
        run: npm i

      - name: Package app
        if: steps.regex-match.outputs.match == ''
        run: npm run make

      - name: Package and Publish app
        if: steps.regex-match.outputs.match != ''
        run: npm run publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


      - name: Build Changelog
        if: matrix.os == 'ubuntu-latest' && steps.regex-match.outputs.match != ''
        id: changelog
        uses: ardalanamini/auto-changelog@v3
        with:
          mention-authors: false
          mention-new-contributors: false
          include-compare: false
          semver: false

      - name: Update release
        if: matrix.os == 'ubuntu-latest' && steps.regex-match.outputs.match != ''
        id: update_release
        uses: meeDamian/github-release@2.0
        with:
          tag: v${{ github.event.head_commit.message }}
          allow_override: true
          token: ${{ secrets.GITHUB_TOKEN }}
          name: Release v${{ github.event.head_commit.message }}
          body: ${{ steps.changelog.outputs.changelog }} &#x20;