name: Build

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v3.6.0
        with:
          node-version: 18
        
      - run: npm i
      - run: npm run publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Changelog
        if: matrix.os == 'ubuntu-latest'
        id: changelog
        uses: ardalanamini/auto-changelog@v3
        with:
          mention-authors: false
          mention-new-contributors: false
          include-compare: false
          semver: false

      - name: Update release
        if: matrix.os == 'ubuntu-latest'
        id: update_release
        uses: meeDamian/github-release@2.0
        with:
          allow_override: true
          token: ${{ secrets.GITHUB_TOKEN }}
          name: Release ${{github.ref_name}}
          body: ${{ steps.changelog.outputs.changelog }} &#x20;